# Generated by Django 5.2.6 on 2025-09-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('BORROWER', 'Borrower'), ('LENDER', 'Lender')], default='BORROWER', max_length=20),
        ),
    ]
