# Generated by Django 5.2.6 on 2025-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
